import csv
import os

topics = [
    # EE: Signals & Systems, Microelectronics, Electromagnetism
    ("Signals and Systems: Continuous-Time Convolution", "Continuous-Time Convolution 1", "MIT OpenCourseWare", ""),
    ("Signals and Systems: Fourier Series", "Fourier Series", "MIT OpenCourseWare", ""),
    ("Signals and Systems: The Laplace Transform", "The Laplace Transform", "MIT OpenCourseWare", ""),
    ("Signals and Systems: The Z-Transform", "The Z-Transform", "MIT OpenCourseWare", ""),
    ("Semiconductor Physics: PN Junction", "PN Junction Diode", "The Organic Chemistry Tutor", ""),
    ("Bipolar Junction Transistor (BJT) Fundamentals", "BJT: Bipolar Junction Transistor", "The Organic Chemistry Tutor", ""),
    ("BJT Small-Signal Analysis", "BJT Small Signal Analysis", "Razavi Electronics", ""),
    ("MOSFET Operation and Characteristics", "MOSFET Device Physics", "Razavi Electronics", ""),
    ("MOSFET Small-Signal Model", "MOSFET Small Signal Model", "Razavi Electronics", ""),
    ("CMOS Inverter Characteristics", "CMOS Inverter", "Razavi Electronics", ""),
    ("Operational Amplifiers (Op-Amps) Ideal Properties", "Operational Amplifiers - Ideal Properties", "Razavi Electronics", ""),
    ("Non-Ideal Op-Amp Effects", "Nonideal Op Amps", "Razavi Electronics", ""),
    ("Electromagnetics: Gauss's Law and Electric Fields", "Gauss's Law", "MIT OpenCourseWare", ""),
    ("Electromagnetics: Ampere's Law and Magnetic Fields", "Ampere's Law", "MIT OpenCourseWare", ""),
    ("Electromagnetics: Faraday's Law of Induction", "Faraday's Law", "MIT OpenCourseWare", ""),
    ("Maxwell's Equations and Electromagnetic Waves", "Maxwell's Equations", "MIT OpenCourseWare", ""),
    ("Transmission Line Theory and Equations", "Transmission Lines - Signal Transmission and Reflection", "MIT OpenCourseWare", ""),
    ("The Smith Chart", "Smith Chart Basics", "TechWorld with Nana", ""),
    ("Waveguides: TE and TM Modes", "Rectangular Waveguides", "nptelhrd", ""),
    ("Antenna Radiation Patterns", "Antenna Basics", "nptelhrd", ""),
    ("Digital Logic: Boolean Algebra and Logic Gates", "Boolean Algebra", "Neso Academy", ""),
    ("Combinational Logic Circuits (Multiplexers and Decoders)", "Multiplexers", "Neso Academy", ""),
    ("Sequential Logic: Flip-Flops and Latches", "Flip Flops", "Neso Academy", ""),
    ("Finite State Machines (FSM)", "Finite State Machines", "Neso Academy", ""),

    # Advanced Pure Math: Real Analysis, Complex Analysis, Abstract Algebra, Topology
    ("Real Analysis: Metric Spaces", "Metric Spaces", "Professor Leonard", ""),
    ("Real Analysis: Sequences and Series of Functions", "Sequences of Functions", "MIT OpenCourseWare", ""),
    ("Real Analysis: Uniform Convergence", "Uniform Convergence", "MIT OpenCourseWare", ""),
    ("Real Analysis: The Riemann-Stieltjes Integral", "Riemann-Stieltjes Integral", "MIT OpenCourseWare", ""),
    ("Real Analysis: Lebesgue Measure", "Lebesgue Measure", "MIT OpenCourseWare", ""),
    ("Complex Analysis: The Cauchy-Riemann Equations", "Cauchy Riemann Equations", "The Math Sorcerer", ""),
    ("Complex Analysis: Cauchy's Integral Theorem", "Cauchy's Integral Theorem", "The Math Sorcerer", ""),
    ("Complex Analysis: Cauchy's Integral Formula", "Cauchy's Integral Formula", "The Math Sorcerer", ""),
    ("Complex Analysis: Taylor and Laurent Series", "Laurent Series", "The Math Sorcerer", ""),
    ("Complex Analysis: The Residue Theorem", "Residue Theorem", "The Math Sorcerer", ""),
    ("Complex Analysis: Conformal Mapping", "Conformal Mappings", "The Math Sorcerer", ""),
    ("Abstract Algebra: Groups and Subgroups", "Group Theory Basics", "The Math Sorcerer", ""),
    ("Abstract Algebra: Cosets and Lagrange's Theorem", "Lagrange's Theorem", "The Math Sorcerer", ""),
    ("Abstract Algebra: Normal Subgroups and Quotient Groups", "Normal Subgroups", "The Math Sorcerer", ""),
    ("Abstract Algebra: Group Homomorphisms and Isomorphisms", "Group Homomorphisms", "The Math Sorcerer", ""),
    ("Abstract Algebra: The Sylow Theorems", "Sylow Theorems", "The Math Sorcerer", ""),
    ("Abstract Algebra: Rings and Fields", "Rings and Fields", "The Math Sorcerer", ""),
    ("Abstract Algebra: Galois Theory", "Galois Theory", "The Math Sorcerer", ""),
    ("Topology: Open and Closed Sets", "Open and Closed Sets", "The Math Sorcerer", ""),
    ("Topology: Compactness", "Compactness", "The Math Sorcerer", ""),
    ("Topology: Connectedness", "Connectedness", "The Math Sorcerer", ""),
    ("Topology: Continuous Functions", "Continuous Functions", "The Math Sorcerer", ""),
    ("Topology: The Fundamental Group", "Fundamental Group", "The Math Sorcerer", ""),

    # Pure Physics & Quantum Mechanics
    ("Quantum Mechanics: The Schrödinger Equation", "Schrodinger Equation", "MIT OpenCourseWare", ""),
    ("Quantum Mechanics: Particle in a 1D Box", "Particle in a Box", "MIT OpenCourseWare", ""),
    ("Quantum Mechanics: The Quantum Harmonic Oscillator", "Quantum Harmonic Oscillator", "MIT OpenCourseWare", ""),
    ("Quantum Mechanics: Orbital Angular Momentum", "Angular Momentum", "MIT OpenCourseWare", ""),
    ("Quantum Mechanics: The Hydrogen Atom", "Hydrogen Atom", "MIT OpenCourseWare", ""),
    ("Quantum Mechanics: Spin and Pauli Matrices", "Spin", "MIT OpenCourseWare", ""),
    ("Quantum Mechanics: Time-Independent Perturbation Theory", "Perturbation Theory", "MIT OpenCourseWare", ""),
    ("Statistical Mechanics: Microstates and Macrostates", "Microstates and Macrostates", "MIT OpenCourseWare", ""),
    ("Statistical Mechanics: The Microcanonical Ensemble", "Microcanonical Ensemble", "MIT OpenCourseWare", ""),
    ("Statistical Mechanics: The Canonical Ensemble", "Canonical Ensemble", "MIT OpenCourseWare", ""),
    ("Statistical Mechanics: The Partition Function", "Partition Function", "MIT OpenCourseWare", ""),
    ("Statistical Mechanics: Bose-Einstein and Fermi-Dirac Statistics", "Quantum Statistics", "MIT OpenCourseWare", ""),
    ("Electrodynamics: Multipole Expansion", "Multipole Expansion", "MIT OpenCourseWare", ""),
    ("Electrodynamics: Electromagnetic Waves in Vacuum", "Electromagnetic Waves", "MIT OpenCourseWare", ""),
    ("Electrodynamics: Retarded Potentials", "Retarded Potentials", "MIT OpenCourseWare", ""),
    ("Electrodynamics: Liénard-Wiechert Potentials", "Lienard-Wiechert Potentials", "MIT OpenCourseWare", ""),
    ("Electrodynamics: Relativistic Electrodynamics", "Relativistic Electrodynamics", "MIT OpenCourseWare", ""),
    ("General Relativity: The Equivalence Principle", "Equivalence Principle", "Stanford", ""),
    ("General Relativity: Tensors and Differential Geometry", "Tensors", "Stanford", ""),
    ("General Relativity: The Geodesic Equation", "Geodesic Equation", "Stanford", ""),
    ("General Relativity: The Riemann Curvature Tensor", "Curvature Tensor", "Stanford", ""),
    ("General Relativity: Einstein's Field Equations", "Einstein Field Equations", "Stanford", ""),
    ("General Relativity: The Schwarzschild Solution", "Schwarzschild Metric", "Stanford", ""),

    # Core Mechanical Engineering
    ("Thermodynamics: The First Law of Thermodynamics", "First Law of Thermodynamics", "LearnChemE", ""),
    ("Thermodynamics: The Second Law and Entropy", "Second Law of Thermodynamics", "LearnChemE", ""),
    ("Thermodynamics: Exergy and Reversibility", "Exergy", "LearnChemE", ""),
    ("Thermodynamics: Vapor Power Cycles (Rankine)", "Rankine Cycle", "LearnChemE", ""),
    ("Thermodynamics: Gas Power Cycles (Brayton)", "Brayton Cycle", "LearnChemE", ""),
    ("Thermodynamics: Refrigeration Cycles", "Refrigeration Cycle", "LearnChemE", ""),
    ("Heat Transfer: Steady-State Conduction", "Conduction Heat Transfer", "LearnChemE", ""),
    ("Heat Transfer: Transient Conduction", "Transient Conduction", "LearnChemE", ""),
    ("Heat Transfer: Free and Forced Convection", "Convection Heat Transfer", "LearnChemE", ""),
    ("Heat Transfer: Thermal Radiation", "Radiation Heat Transfer", "LearnChemE", ""),
    ("Heat Transfer: Heat Exchanger Design (LMTD & NTU)", "Heat Exchangers", "LearnChemE", ""),
    ("Solid Mechanics: Stress and Strain Analysis", "Stress and Strain", "The Efficient Engineer", ""),
    ("Solid Mechanics: Mohr's Circle", "Mohr's Circle", "The Efficient Engineer", ""),
    ("Solid Mechanics: Hooke's Law and Material Properties", "Hooke's Law", "The Efficient Engineer", ""),
    ("Solid Mechanics: Bending Moments and Shear Force Diagrams", "Shear and Moment Diagrams", "The Efficient Engineer", ""),
    ("Solid Mechanics: Deflection of Beams", "Beam Deflection", "The Efficient Engineer", ""),
    ("Solid Mechanics: Torsion of Circular Shafts", "Torsion", "The Efficient Engineer", ""),
    ("Solid Mechanics: Failure Theories (Von Mises & Tresca)", "Von Mises Yield Criterion", "The Efficient Engineer", ""),
    ("Fluid Dynamics: Fluid Statics and Manometry", "Fluid Statics", "LearnChemE", ""),
    ("Fluid Dynamics: The Bernoulli Equation", "Bernoulli Equation", "LearnChemE", ""),
    ("Fluid Dynamics: Navier-Stokes Equations", "Navier-Stokes Equations", "LearnChemE", ""),
    ("Fluid Dynamics: Boundary Layer Theory", "Boundary Layer", "LearnChemE", ""),
    ("Fluid Dynamics: Flow in Pipes and Friction Losses", "Pipe Flow", "LearnChemE", ""),
    ("Fluid Dynamics: Drag and Lift", "Drag and Lift", "LearnChemE", ""),

    # Organic & Physical Chemistry
    ("Organic Chemistry: SN1 and SN2 Nucleophilic Substitution", "SN1 SN2 E1 E2 Reactions", "The Organic Chemistry Tutor", ""),
    ("Organic Chemistry: E1 and E2 Elimination Reactions", "Elimination Reactions", "The Organic Chemistry Tutor", ""),
    ("Organic Chemistry: Electrophilic Addition to Alkenes", "Alkene Reactions", "The Organic Chemistry Tutor", ""),
    ("Organic Chemistry: Electrophilic Aromatic Substitution (EAS)", "Electrophilic Aromatic Substitution", "The Organic Chemistry Tutor", ""),
    ("Organic Chemistry: Nucleophilic Acyl Substitution", "Nucleophilic Acyl Substitution", "The Organic Chemistry Tutor", ""),
    ("Organic Chemistry: The Aldol Condensation", "Aldol Condensation", "The Organic Chemistry Tutor", ""),
    ("Organic Chemistry: Grignard Reagents and Organometallics", "Grignard Reagents", "The Organic Chemistry Tutor", ""),
    ("Stereochemistry: Chirality and Stereocenters", "Chirality", "The Organic Chemistry Tutor", ""),
    ("Stereochemistry: Enantiomers and Diastereomers", "Enantiomers and Diastereomers", "The Organic Chemistry Tutor", ""),
    ("Stereochemistry: R and S Configuration (Cahn-Ingold-Prelog)", "R and S Configuration", "The Organic Chemistry Tutor", ""),
    ("Stereochemistry: Fischer Projections", "Fischer Projections", "The Organic Chemistry Tutor", ""),
    ("Stereochemistry: Conformations of Cyclohexane", "Cyclohexane Chair Conformations", "The Organic Chemistry Tutor", ""),
    ("Spectroscopy: Nuclear Magnetic Resonance (NMR)", "NMR Spectroscopy", "The Organic Chemistry Tutor", ""),
    ("Spectroscopy: Infrared (IR) Spectroscopy", "IR Spectroscopy", "The Organic Chemistry Tutor", ""),
    ("Physical Chemistry: Chemical Kinetics and Rate Laws", "Rate Laws", "The Organic Chemistry Tutor", ""),
    ("Physical Chemistry: The Arrhenius Equation and Activation Energy", "Arrhenius Equation", "The Organic Chemistry Tutor", ""),
    ("Physical Chemistry: Catalysis and Reaction Mechanisms", "Catalysts and Reaction Mechanisms", "The Organic Chemistry Tutor", ""),
    ("Physical Chemistry: Gibbs Free Energy and Spontaneity", "Gibbs Free Energy", "The Organic Chemistry Tutor", ""),
    ("Physical Chemistry: Chemical Potential and Phase Equilibria", "Chemical Potential", "TMP Chem", ""),
    ("Physical Chemistry: The Clausius-Clapeyron Equation", "Clausius-Clapeyron Equation", "The Organic Chemistry Tutor", ""),
    ("Physical Chemistry: Ideal and Non-Ideal Solutions (Raoult's Law)", "Raoult's Law", "The Organic Chemistry Tutor", ""),
    ("Quantum Chemistry: The Particle in a 1D Box", "Particle in a 1D Box", "TMP Chem", ""),
    ("Quantum Chemistry: The Rigid Rotor Model", "Rigid Rotor", "TMP Chem", ""),
    ("Quantum Chemistry: The Harmonic Oscillator Model", "Quantum Harmonic Oscillator", "TMP Chem", ""),
    ("Quantum Chemistry: Molecular Orbital Theory", "Molecular Orbital Theory", "The Organic Chemistry Tutor", "")
]

csv_path = os.path.join(os.path.dirname(__file__), '..', '..', 'curated_topics_blueprint.csv')

with open(csv_path, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for topic in topics:
        writer.writerow(topic)

print(f"Appended {len(topics)} new STEM topics to curated_topics_blueprint.csv")
