import json
import time
import asyncio
import os
import sys
import uuid
import re
from pathlib import Path
from dotenv import load_dotenv

# Ensure we can import from app
sys.path.append(str(Path(__file__).resolve().parent.parent))

from app.utils.ai_client import generate_text, clean_json_string
from app.utils.youtube_client import search_youtube_videos
from app.core.config import settings

def generate_html(roadmap_data, filename, model_label):
    title = roadmap_data.get("title", "Untitled Roadmap")
    desc = roadmap_data.get("description", "")
    modules = roadmap_data.get("roadmap_plan", {}).get("modules", [])
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{title}</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 20px; background: #f0f7f6; color: #333; }}
            .header {{ border-bottom: 4px solid #0f766e; padding-bottom: 20px; margin-bottom: 30px; }}
            .model-tag {{ display: inline-block; background: #0f766e; color: white; padding: 4px 12px; font-size: 12px; font-weight: bold; border-radius: 20px; margin-bottom: 10px; }}
            h1 {{ color: #0f766e; margin: 0; }}
            .module {{ background: white; border: 1px solid #ddd; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }}
            .module-title {{ color: #0f766e; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-top: 0; }}
            .pow {{ background: #fffbeb; border-left: 4px solid #f59e0b; padding: 15px; margin: 15px 0; font-size: 14px; }}
            .topic {{ margin-left: 20px; margin-bottom: 15px; }}
            .youtube-link {{ color: #ef4444; text-decoration: none; font-weight: bold; display: flex; align-items: center; gap: 5px; }}
            .youtube-link:hover {{ text-decoration: underline; }}
            .metadata {{ color: #666; font-size: 12px; margin-top: 5px; }}
            .resources {{ border-top: 1px solid #eee; padding-top: 10px; margin-top: 15px; font-size: 13px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <span class="model-tag">GENERATED BY {model_label}</span>
            <h1>{title}</h1>
            <p>{desc}</p>
            <div class="metadata">Depth Score: {roadmap_data.get('depth_score')} | Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}</div>
        </div>
    """
    
    for mod in modules:
        html += f"""
        <div class="module">
            <h2 class="module-title">{mod.get('title')} ({mod.get('timeline')})</h2>
            <p><strong>Outcome:</strong> {mod.get('outcome')}</p>
            
            <div class="pow">
                <strong>🛠️ Proof of Work:</strong> {mod.get('proof_of_work_instructions', {}).get('what_to_build')}<br/>
                <small>Evidence: {mod.get('proof_of_work_instructions', {}).get('what_counts_as_evidence')}</small>
            </div>

            <h3>Topics & Learning Resources</h3>
        """
        
        for topic in mod.get("topics", []):
            yt_id = topic.get("youtube_video_id")
            yt_title = topic.get("youtube_video_title")
            duration = topic.get("duration")
            
            html += f"""
            <div class="topic">
                <strong>• {topic.get('title')}</strong>
            """
            
            if yt_id:
                html += f"""
                <a href="https://www.youtube.com/watch?v={yt_id}" class="youtube-link" target="_blank">
                    📺 Watch: {yt_title} ({duration} mins)
                </a>
                """
            else:
                html += f"<br/><small style='color: #999;'>No relevant video found.</small>"
                
            html += "</div>"
            
        if mod.get("resources"):
            html += '<div class="resources"><strong>External Links:</strong><ul>'
            for res in mod.get("resources", []):
                html += f'<li><a href="{res.get("url")}">{res.get("title")}</a> ({res.get("type")})</li>'
            html += '</ul></div>'
            
        html += "</div>"
        
    html += "</body></html>"
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"📁 Report generated: {filename}")

async def full_production_lifecycle(model_name, label, output_file, subject="React Native"):
    print(f"\n⚡ Processing FULL FLOW for {label} ({model_name})...")
    
    prompt = f"""
    You are an expert curriculum designer. Generate a 1-week learning roadmap for '{subject}'.
    Output JSON ONLY. Adhere to this exact schema:
    {{
      "title": "string",
      "description": "string",
      "depth_score": number,
      "roadmap_plan": {{
        "modules": [
          {{
            "title": "string",
            "outcome": "string",
            "timeline": "string",
            "proof_of_work_instructions": {{
              "what_to_build": "string",
              "what_counts_as_evidence": "string",
              "eval_criteria": ["string", "string"]
            }},
            {{ "title": "string", "subtopics": [{{ "title": "string" }}] }},
            "resources": [
              {{ "title": "string", "url": "string", "type": "video|docs|article" }}
            ]
          }}
        ]
      }}
    }}
    """
    
    # 1. AI Generation
    try:
        raw_text = await generate_text(prompt, model=model_name, response_mime_type="application/json")
        cleaned = clean_json_string(raw_text)
        roadmap_data = json.loads(cleaned)
        print(f"✨ AI content generated.")
    except Exception as e:
        print(f"❌ AI Generation Failed: {e}")
        return

    # 2. ID Injection (Production Logic)
    for m_idx, module in enumerate(roadmap_data["roadmap_plan"]["modules"]):
        module["id"] = f"module_{m_idx + 1}"
        for t_idx, topic in enumerate(module.get("topics", [])):
            topic["id"] = f"topic_{m_idx + 1}_{t_idx + 1}"
            topic["uuid"] = str(uuid.uuid4())
            for subtopic in topic.get("subtopics", []):
                subtopic["id"] = str(uuid.uuid4())
    print(f"🆔 IDs and UUIDs injected.")

    # 3. YouTube Enrichment (Production Logic)
    if settings.YOUTUBE_API_KEY:
        print(f"🎬 Searching YouTube videos (this may take a moment)...")
        used_video_ids = set()
        for module in roadmap_data["roadmap_plan"]["modules"]:
            for topic in module.get("topics", []):
                subtopic_context = " ".join([st.get("title", "") for st in topic.get("subtopics", [])[:2]])
                search_query = f"{subject} {topic['title']} {subtopic_context} tutorial"
                
                results = await search_youtube_videos(search_query, max_results=5)
                relevance_keywords = set(re.findall(r'\w+', f"{topic['title']} {subtopic_context}".lower()))
                
                chosen_video = None
                for res in results:
                    if res["video_id"] in used_video_ids: continue
                    video_title_lower = res["video_title"].lower()
                    is_relevant = any(kw in video_title_lower for kw in relevance_keywords if len(kw) >= 4)
                    if is_relevant:
                        chosen_video = res
                        used_video_ids.add(res["video_id"])
                        break
                
                if chosen_video:
                    topic["youtube_video_id"] = chosen_video["video_id"]
                    topic["youtube_video_title"] = chosen_video["video_title"]
                    topic["duration"] = chosen_video["duration_minutes"]
                elif results:
                    topic["youtube_video_id"] = results[0]["video_id"]
                    topic["youtube_video_title"] = results[0]["video_title"]
                    topic["duration"] = results[0]["duration_minutes"]
                
                await asyncio.sleep(0.1) # Throttling
        print(f"✅ YouTube enrichment complete.")
    else:
        print(f"⚠️ Skipping YouTube (No API Key).")

    # 4. Generate HTML
    generate_html(roadmap_data, output_file, label)

async def main():
    load_dotenv(Path(__file__).resolve().parent.parent / ".env")
    
    print("🔬 Full-Flow Production Test: AI + Logic + YouTube")
    print("==================================================")
    
    # Run both
    await full_production_lifecycle("models/gemini-2.5-flash", "FREE_TIER", "flash_roadmap.html")
    await full_production_lifecycle("models/gemini-2.5-pro", "PAID_TIER", "pro_roadmap.html")
    
    print("\n==================================================")
    print("Done. Check flash_roadmap.html and pro_roadmap.html")

if __name__ == "__main__":
    asyncio.run(main())
