import React from 'react';
import { Metadata } from 'next';
import ResearchLabDetailClient from './ResearchLabDetailClient';
import UserNav from '@/components/UserNav';
import Link from 'next/link';
export const metadata: Metadata = {
  title: 'Technical Report | EulerFold Decode',
  description: 'Technical mastery report generated by EulerFold Decode.',
};

export default function ResearchLabDetailPage({ params }: { params: { id: string } }) {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <header className="inconsolata-ui border-b border-border bg-header h-[48px] shrink-0 z-50 sticky top-0 inset-x-0">
          <div className="w-full px-4 md:px-6 flex h-full items-center justify-between">
              <div className="flex items-center gap-2 md:gap-4">
                  <Link className="flex items-center group shrink-0" href="/dashboard" aria-label="Dashboard">
                      <img src="/apple-touch-icon.png" alt="EulerFold" className="w-7 h-7 group-hover:opacity-80 transition-opacity" />
                  </Link>
              </div>
              <div className="flex items-center gap-4">
                  <UserNav />
              </div>
          </div>
      </header>
      <main className="flex-grow min-w-0">
        <ResearchLabDetailClient id={params.id} />
      </main>
    </div>
  );
}
