import React from 'react';
import { Metadata } from 'next';
import ResearchLabDetailClient from './ResearchLabDetailClient';

export const metadata: Metadata = {
  title: 'Technical Report | EulerFold Research Lab',
  description: 'Technical mastery report generated by EulerFold Research Lab.',
};

export default function ResearchLabDetailPage({ params }: { params: { id: string } }) {
  return (
    <div className="min-h-screen bg-background">
      <ResearchLabDetailClient id={params.id} />
    </div>
  );
}
