"use client";

import React, { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import RoadmapGenerator from '@/components/landing/RoadmapGenerator';
import RoadmapDisplay from '@/components/landing/RoadmapDisplay';
import JobDecodedGenerator from '@/components/job-decoded/JobDecodedGenerator';
import GenerateFromLink from '@/components/landing/GenerateFromLink';
import GenerateFromSyllabus from '@/components/landing/GenerateFromSyllabus';
import KnowledgeGapQuiz from '@/components/landing/KnowledgeGapQuiz';
import { RoadmapData, ExploreRoadmap } from '@/lib/api';
import EulerLogoCanvas from '@/components/EulerLogoCanvas';
import { 
  Sparkles,
  Briefcase,
  HelpCircle,
  FileText,
  CheckCircle2,
  TrendingUp,
  ArrowRight,
  Calendar,
  Zap,
  BookOpen,
  Library,
  Microscope,
  Archive,
  GraduationCap,
  Compass,
  ChevronDown,
  Link2,
  Target
} from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import PublicHeader from '@/components/PublicHeader';

type Mode = 'ai' | 'job' | 'url' | 'syllabus' | 'gaps';

const MODE_CONFIG: { id: Mode; label: string; icon: React.ElementType; desc: string; color: string; activeColor: string }[] = [
  { id: 'ai', label: 'AI Gen', icon: Sparkles, desc: 'From any topic', color: 'text-accent', activeColor: 'bg-accent' },
  { id: 'job', label: 'Job Decoded', icon: Briefcase, desc: 'From a job post', color: 'text-teal-600', activeColor: 'bg-teal-600' },
  { id: 'url', label: 'From Link', icon: Link2, desc: 'From a URL', color: 'text-indigo-500', activeColor: 'bg-indigo-500' },
  { id: 'syllabus', label: 'Syllabus', icon: BookOpen, desc: 'From course text', color: 'text-amber-600', activeColor: 'bg-amber-600' },
  { id: 'gaps', label: 'Skill Quiz', icon: Target, desc: 'Find your gaps', color: 'text-rose-500', activeColor: 'bg-rose-500' },
];

function InstructionsSidePanel({ mode }: { mode: Mode }) {
  const [openSection, setOpenSection] = useState<'instructions' | 'faq' | null>(null);

  const instructions: Record<Mode, string[]> = {
    ai: [
      "Be specific about your goal. Instead of 'Learn Python', try 'Build scalable backend APIs in Python'.",
      "Select a timeline that matches your realistic schedule.",
      "Our AI autonomously browses the web to attach verified, cutting-edge resources to every topic."
    ],
    job: [
      "Paste the entire job description directly from LinkedIn, Indeed, or anywhere else.",
      "Make sure it includes the 'Requirements' or 'What you'll do' section.",
      "The AI will extract all hard skills and map them into a tailored curriculum."
    ],
    url: [
      "Paste a direct link to a GitHub repository, blog post, or technical documentation.",
      "Make sure the link is publicly accessible (no login required).",
      "The AI will deconstruct the topic and build a course leading up to that exact knowledge."
    ],
    syllabus: [
      "Paste plain text from a course syllabus or textbook table of contents.",
      "Ensure the text has a clear hierarchical structure (Chapters, Modules).",
      "We will translate the static topics into an interactive EulerFold course."
    ],
    gaps: [
      "Enter your target role and a few skills you already know.",
      "Take the 5-minute diagnostic quiz generated by the AI.",
      "Based on what you get wrong, we'll build a course strictly focused on filling your knowledge gaps."
    ]
  };

  const faqs: Record<Mode, { q: string; a: string }[]> = {
    ai: [
      { q: "How are references verified?", a: "The AI executes real-time DuckDuckGo searches for every module to guarantee live, authoritative references." },
      { q: "What is Local AI Mode?", a: "It runs models directly on your device via WebGPU, ensuring total privacy since no data leaves your machine." },
      { q: "What is OpenRouter?", a: "It's a unified API gateway that lets you access multiple AI models through a single interface using your own key." }
    ],
    job: [
      { q: "What is Job Decoded?", a: "Paste any job description text to instantly generate a targeted course tailored exactly to those requirements." },
      { q: "Does it guarantee a job?", a: "While it teaches the exact skills requested by the employer, your project portfolio and interview execution still determine the outcome." },
      { q: "How are references verified?", a: "The AI executes real-time DuckDuckGo searches for every module to guarantee live, authoritative references." }
    ],
    url: [
      { q: "What links work best?", a: "GitHub repositories, technical articles, arXiv papers, and public software documentation." },
      { q: "Can it bypass paywalls?", a: "No, the AI can only access and deconstruct content that is publicly available on the web." },
      { q: "Is this a Pro feature?", a: "Yes, URL deconstruction requires our highest-capability AI pipeline and is exclusive to Pro members." }
    ],
    syllabus: [
      { q: "How do I format the syllabus?", a: "Plain text with clear line breaks works best. Don't worry about perfect formatting, our AI understands most academic structures." },
      { q: "Will it change the course length?", a: "The course will be adapted to fit your requested time value (e.g., 4 weeks) while covering the original subjects." },
      { q: "Is this a Pro feature?", a: "Yes, translating static syllabi into interactive courses is exclusive to Pro members." }
    ],
    gaps: [
      { q: "How many questions are in the quiz?", a: "Typically 5-10 multiple choice questions dynamically generated based on your target role." },
      { q: "What if I get everything right?", a: "The AI will generate an advanced course to push your skills even further." },
      { q: "Is this a Pro feature?", a: "Yes, diagnostic auditing is an intensive operation exclusive to Pro members." }
    ]
  };

  const currentInstructions = instructions[mode];
  const currentFaqs = faqs[mode];
  
  const commonFaqs = [
    { q: "How long does generation take?", a: "Usually 20-40 seconds depending on the complexity of the live web searches." },
    { q: "Can I edit my course later?", a: "Yes! Course owners get full editing tools on their dashboard to customize the content." }
  ];

  const allFaqs = [...currentFaqs, ...commonFaqs];

  return (
    <div className="flex flex-col gap-3 animate-in fade-in slide-in-from-left-4 duration-700">
      <div className="bg-sidebar/60 border border-border/60 rounded-lg overflow-hidden">
        <button 
          onClick={() => setOpenSection(openSection === 'instructions' ? null : 'instructions')}
          className="w-full flex items-center justify-between p-3.5 hover:bg-sidebar/80 transition-colors"
        >
          <div className="flex items-center gap-2">
            <FileText className="w-3.5 h-3.5 text-accent" />
            <span className="text-[12px] font-bold text-text-heading">Tips</span>
          </div>
          <ChevronDown className={`w-3.5 h-3.5 text-text-muted transition-transform duration-300 ${openSection === 'instructions' ? 'rotate-180' : ''}`} />
        </button>
        <div className={`transition-all duration-300 ease-in-out overflow-hidden ${openSection === 'instructions' ? 'max-h-96 border-t border-border/40' : 'max-h-0'}`}>
          <div className="p-3.5 bg-background/50">
            <ul className="space-y-2.5">
              {currentInstructions.map((inst, idx) => (
                <li key={idx} className="flex items-start gap-2 text-[11px] text-text-muted leading-relaxed">
                  <CheckCircle2 className="w-3 h-3 mt-0.5 text-accent shrink-0" />
                  <span>{inst}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      <div className="bg-sidebar/60 border border-border/60 rounded-lg overflow-hidden">
        <button 
          onClick={() => setOpenSection(openSection === 'faq' ? null : 'faq')}
          className="w-full flex items-center justify-between p-3.5 hover:bg-sidebar/80 transition-colors"
        >
          <div className="flex items-center gap-2">
            <HelpCircle className="w-3.5 h-3.5 text-accent" />
            <span className="text-[12px] font-bold text-text-heading">FAQ</span>
          </div>
          <ChevronDown className={`w-3.5 h-3.5 text-text-muted transition-transform duration-300 ${openSection === 'faq' ? 'rotate-180' : ''}`} />
        </button>
        <div className={`transition-all duration-300 ease-in-out overflow-hidden ${openSection === 'faq' ? 'max-h-[800px] border-t border-border/40' : 'max-h-0'}`}>
          <div className="p-3.5 bg-background/50 space-y-3 overflow-y-auto max-h-[60vh]">
            {allFaqs.map((faq, idx) => (
              <div key={idx} className={idx > currentFaqs.length - 1 ? "pt-2 border-t border-border/40" : ""}>
                <h4 className="text-[11px] font-bold text-text-heading mb-0.5">{faq.q}</h4>
                <p className="text-[10px] text-text-muted leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default function InlineGenerator({ 
  featuredRoadmaps, 
  initialSubject = '' 
}: { 
  featuredRoadmaps?: ExploreRoadmap[];
  initialSubject?: string;
}) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const initialMode = (searchParams.get('mode') as Mode) || 'ai';

  const [roadmapData, setRoadmapData] = useState<RoadmapData | null>(null);
  const [generatedFormData, setGeneratedFormData] = useState<any | null>(null);
  const [profile, setProfile] = useState<any>(null);
  const [mode, setMode] = useState<Mode>(initialMode);
  const [isRedirecting, setIsRedirecting] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const m = searchParams.get('mode');
    if (['ai', 'job', 'url', 'syllabus', 'gaps'].includes(m as string)) {
      setMode(m as Mode);
    }
  }, [searchParams]);

  useEffect(() => {
    const fetchProfile = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.user) {
        const { data } = await supabase
          .from('profiles')
          .select('*')
          .eq('supabase_uid', session.user.id)
          .single();
        if (data) setProfile(data);
      }
    };
    fetchProfile();
  }, []);

  const handleRoadmapGenerated = (data: RoadmapData, formData: any) => {
    const timestamp = Date.now();
    localStorage.setItem('last_generated_roadmap', JSON.stringify({ data, timestamp }));
    localStorage.setItem('last_generated_form_data', JSON.stringify({ data: formData, timestamp }));
    sessionStorage.setItem('roadmap_just_generated', 'true');
    
    if ((data as any).slug || data.id) {
      setIsRedirecting(true);
      router.push(`/roadmap/${(data as any).slug || data.id}`);
    } else {
      setRoadmapData(data);
      setGeneratedFormData(formData);
    }
  };

  const handleReset = () => {
    setRoadmapData(null);
    setGeneratedFormData(null);
    localStorage.removeItem('last_generated_roadmap');
    localStorage.removeItem('last_generated_form_data');
    sessionStorage.removeItem('roadmap_just_generated');
  };

  const activeConfig = MODE_CONFIG.find(m => m.id === mode)!;

  return (
    <div className="flex flex-col bg-transparent manrope-body selection:bg-teal-500/30 w-full animate-in fade-in zoom-in-95 duration-500">

      {isRedirecting && (
        <div className="fixed inset-0 z-[200] bg-background/95 backdrop-blur-3xl flex flex-col items-center justify-center animate-in fade-in duration-500">
          <div className="flex flex-col items-center gap-6">
            <div className="flex flex-col items-center gap-4">
              <p className="inconsolata-ui text-[14px] font-bold text-text-heading tracking-[0.2em] uppercase">
                Finalizing Your Course
              </p>
              <div className="flex gap-1.5">
                {[0, 1, 2].map(i => (
                  <div 
                    key={i} 
                    className="w-1.5 h-1.5 bg-accent rounded-full animate-bounce" 
                    style={{ animationDelay: `${i * 0.2}s` }} 
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="flex-1 flex flex-col relative">
        <main className="flex-1 min-w-0 bg-background scroll-smooth">
          
          {/* Modernized Hero Section */}
          {!roadmapData && !isLoading && (
            <div className="relative pt-4 pb-8 overflow-hidden">
              
              <div className="max-w-3xl mx-auto px-6">

                {/* Mode Selector — Modern pill tabs */}
                <div className="flex flex-wrap items-center justify-center gap-1.5 md:gap-2 animate-in fade-in slide-in-from-bottom-4 duration-700">
                  {MODE_CONFIG.map((m) => {
                    const Icon = m.icon;
                    const isActive = mode === m.id;
                    return (
                      <button
                        key={m.id}
                        onClick={() => {
                          setMode(m.id);
                          if (window.innerWidth < 768) document.getElementById('generator-workspace')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
                        }}
                        className={`group relative flex items-center gap-1.5 md:gap-2 px-3 md:px-4 py-2 md:py-2.5 rounded-lg text-[11px] md:text-[12px] font-bold transition-all duration-300 ${
                          isActive
                            ? `${m.activeColor} text-white shadow-sm ring-1 ring-white/20`
                            : 'bg-sidebar/70 border border-border/60 text-text-heading hover:bg-sidebar hover:border-border'
                        }`}
                      >
                        <Icon className={`w-3.5 h-3.5 ${isActive ? 'text-white' : m.color}`} />
                        <span>{m.label}</span>
                      </button>
                    );
                  })}
                </div>

                {/* Active mode description */}
                <AnimatePresence mode="wait">
                  <motion.p
                    key={mode}
                    initial={{ opacity: 0, y: 4 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -4 }}
                    transition={{ duration: 0.2 }}
                    className="text-center text-[11px] text-text-muted font-medium mt-4"
                  >
                    {activeConfig.desc}
                  </motion.p>
                </AnimatePresence>
              </div>
            </div>
          )}

          <div id="generator-workspace" className="max-w-4xl w-full mx-auto py-2 md:py-4">
            <div className="flex flex-col max-w-2xl mx-auto w-full gap-8 lg:gap-10">
              
              {/* Main Content Column */}
              <div className="min-w-0 w-full">
                
                {!roadmapData ? (
                  <AnimatePresence mode="wait">
                    <motion.div 
                      key={mode} 
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -8 }}
                      transition={{ duration: 0.2, ease: "easeOut" }}
                    >
                      {mode === 'ai' && (
                        <RoadmapGenerator 
                          onRoadmapGenerated={handleRoadmapGenerated} 
                          onLoadingChange={setIsLoading}
                          initialGoal={initialSubject}
                        />
                      )}
                      {mode === 'job' && (
                        <JobDecodedGenerator 
                          onRoadmapGenerated={handleRoadmapGenerated} 
                          onLoadingChange={setIsLoading}
                        />
                      )}
                      {mode === 'url' && (
                        <GenerateFromLink 
                          onRoadmapGenerated={handleRoadmapGenerated} 
                          onLoadingChange={setIsLoading}
                        />
                      )}
                      {mode === 'syllabus' && (
                        <GenerateFromSyllabus 
                          onRoadmapGenerated={handleRoadmapGenerated} 
                          onLoadingChange={setIsLoading}
                        />
                      )}
                      {mode === 'gaps' && (
                        <KnowledgeGapQuiz 
                          onRoadmapGenerated={handleRoadmapGenerated} 
                          onLoadingChange={setIsLoading}
                        />
                      )}

                      {!isLoading && (
                        <div className="mt-8 animate-in fade-in slide-in-from-bottom-4 duration-700 delay-200">
                          <InstructionsSidePanel mode={mode} />
                        </div>
                      )}

                    </motion.div>
                  </AnimatePresence>
                ) : (
                  <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
                    <div className="mb-8 flex items-center justify-between">
                      <button 
                        onClick={handleReset}
                        className="inline-flex items-center px-4 py-1.5 bg-sidebar/60 text-text-primary border border-border text-[11px] font-bold rounded-md hover:bg-sidebar transition-all"
                      >
                        ← Create Another
                      </button>
                    </div>
                    <RoadmapDisplay 
                      roadmapData={roadmapData} 
                      initialFormData={generatedFormData} 
                      justGenerated={true}
                      onSignInRequired={() => router.push(`/login?next=${encodeURIComponent(window.location.pathname)}`)}
                    />
                  </div>
                )}
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
