-- Create recall_responses table to store short-answer recall checks from weekly emails

CREATE TABLE IF NOT EXISTS recall_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_uuid TEXT,
  submission_id BIGINT,
  roadmap_id BIGINT,
  module_number INTEGER,
  question TEXT,
  answer TEXT,
  user_email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS recall_responses_entry_idx ON recall_responses(entry_uuid);
CREATE INDEX IF NOT EXISTS recall_responses_submission_idx ON recall_responses(submission_id);
CREATE INDEX IF NOT EXISTS recall_responses_roadmap_idx ON recall_responses(roadmap_id);
